shamefullyHoist: true
strictPeerDependencies: false
gitChecks: false
packages:
  - "playground"
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
