import { createApp, onBeforeUnmount, onMounted, watch } from 'vue'
import type { Ref, WatchStopHandle, App } from 'vue'
import { useRouter } from 'vue-router'
import { CwaLink } from '#components'

export const useHtmlContent = (container: Ref<null | HTMLElement>) => {
  const router = useRouter()
  let watchStopHandle: undefined | WatchStopHandle

  function convertAnchor(anchor: HTMLElement): App<Element> | undefined {
    const href = anchor.getAttribute('href')
    if (!href) {
      return
    }

    // urls such as "0" which are generated by lipsum are not valid and cause an error in Vue Router
    function hrefToUrl(href: string) {
      try {
        const url = new URL(href)
        // Same-host absolute URLs — strip origin so the router treats them as internal paths.
        // Hostname-only comparison (not full origin) handles dev environments where links may be
        // stored without the port (e.g. https://localhost/page vs https://localhost:3002/page).
        if (typeof window !== 'undefined' && url.hostname === window.location.hostname) {
          return url.pathname + url.search + url.hash
        }
        return href
      }
      catch (err) {
        // Absolute paths starting with '/' are valid router paths — return as-is
        if (href.startsWith('/')) return href
        // Bare words (e.g. lipsum "0") — prefix with // to treat as external rather than router path
        return `//${href}`
      }
    }

    const props: any = {
      to: hrefToUrl(href),
      noPrefetch: undefined,
      prefetch: false,
      noRel: undefined,
      innerHTML: anchor.innerHTML,
    }

    for (const attr of anchor.attributes) {
      if (!['href'].includes(attr.name)) {
        const anchorAttr = anchor.getAttribute(attr.name)
        if (anchorAttr) {
          props[attr.name] = anchorAttr
        }
      }
    }

    const app = createApp(CwaLink, { ...props })
    app.use(router)
    return app
  }

  function replaceAnchors() {
    if (typeof container.value?.getElementsByTagName !== 'function') {
      return
    }
    const anchors: HTMLCollectionOf<HTMLAnchorElement> = container.value.getElementsByTagName('a')
    Array.from(anchors).forEach((anchor: HTMLElement) => {
      // Attempt to create a NuxtLink from the anchor
      const nuxtLink = convertAnchor(anchor)
      if (nuxtLink) {
        // If successful replace the anchor with a span to act as the container for the component
        const parent = anchor.parentNode
        if (parent) {
          const linkContainer = document.createElement('span')
          parent.replaceChild(linkContainer, anchor)
          // mount the NuxtLink component in the span
          nuxtLink.mount(linkContainer)
        }
      }
    })
  }

  onMounted(() => {
    watchStopHandle = watch(container, replaceAnchors, {
      immediate: true,
    })
  })

  onBeforeUnmount(() => {
    watchStopHandle && watchStopHandle()
  })
}
