import { createApp, h, onBeforeUnmount, onMounted, toValue, watch } from 'vue'
import type { Ref, WatchStopHandle, App, MaybeRefOrGetter } from 'vue'
import { useRouter } from 'vue-router'
import { CwaLink } from '#components'

export const useHtmlContent = (container: Ref<null | HTMLElement>, html?: MaybeRefOrGetter<string | undefined>) => {
  const router = useRouter()
  let watchStopHandle: undefined | WatchStopHandle
  const mountedApps: App<Element>[] = []

  function convertAnchor(anchor: HTMLElement): App<Element> | undefined {
    const href = anchor.getAttribute('href')
    if (!href) {
      return
    }

    // urls such as "0" which are generated by lipsum are not valid and cause an error in Vue Router
    function hrefToUrl(href: string) {
      try {
        const url = new URL(href)
        if (typeof window !== 'undefined' && url.hostname === window.location.hostname) {
          return url.pathname + url.search + url.hash
        }
        return href
      }
      catch (err) {
        if (href.startsWith('/')) return href
        return `//${href}`
      }
    }

    const linkProps: any = {
      to: hrefToUrl(href),
      noPrefetch: undefined,
      prefetch: false,
      noRel: undefined,
    }

    for (const attr of anchor.attributes) {
      if (!['href', 'target'].includes(attr.name)) {
        const anchorAttr = anchor.getAttribute(attr.name)
        if (anchorAttr) {
          linkProps[attr.name] = anchorAttr
        }
      }
    }

    const innerHtml = anchor.innerHTML
    const app = createApp({
      render() {
        return h(CwaLink, linkProps, {
          default: () => h('span', { innerHTML: innerHtml }),
        })
      },
    })
    app.use(router)
    return app
  }

  function unmountApps() {
    while (mountedApps.length) {
      mountedApps.pop()?.unmount()
    }
  }

  function replaceAnchors() {
    unmountApps()

    if (typeof container.value?.getElementsByTagName !== 'function') {
      return
    }
    const anchors: HTMLCollectionOf<HTMLAnchorElement> = container.value.getElementsByTagName('a')
    Array.from(anchors).forEach((anchor: HTMLElement) => {
      // Attempt to create a NuxtLink from the anchor
      const nuxtLink = convertAnchor(anchor)
      if (nuxtLink) {
        // If successful replace the anchor with a span to act as the container for the component
        const parent = anchor.parentNode
        if (parent) {
          const linkContainer = document.createElement('span')
          parent.replaceChild(linkContainer, anchor)
          // mount the NuxtLink component in the span
          nuxtLink.mount(linkContainer)
          mountedApps.push(nuxtLink)
        }
      }
    })
  }

  onMounted(() => {
    watchStopHandle = watch([container, () => toValue(html)], replaceAnchors, {
      immediate: true,
      flush: 'post',
    })
  })

  onBeforeUnmount(() => {
    watchStopHandle && watchStopHandle()
    unmountApps()
  })
}
