import { createApp, onBeforeUnmount, onMounted, resolveComponent, watch } from 'vue'
import type { Ref, WatchStopHandle, App } from 'vue'
import { CwaLink } from '#components'

export const useHtmlContent = (container: Ref<null | HTMLElement>) => {
  let watchStopHandle: undefined | WatchStopHandle

  function convertAnchor(anchor: HTMLElement): App<Element> | undefined {
    const href = anchor.getAttribute('href')
    if (!href) {
      return
    }

    // urls such as "0" which are generated by lipsum are not valid and cause an error in Vue Router
    function hrefToUrl(href: string) {
      try {
        new URL(href)
        return href
      }
      catch (err) {
        return `//${href}`
      }
    }

    const props: any = {
      to: hrefToUrl(href),
      noPrefetch: undefined,
      prefetch: false,
      noRel: undefined,
      innerHTML: anchor.innerHTML,
    }

    for (const attr of anchor.attributes) {
      if (!['href'].includes(attr.name)) {
        const anchorAttr = anchor.getAttribute(attr.name)
        if (anchorAttr) {
          props[attr.name] = anchorAttr
        }
      }
    }
    const rlComponent = resolveComponent('RouterLink')
    if (typeof rlComponent === 'string') {
      return
    }

    const app = createApp(CwaLink, {
      ...props,
    })
    app.component('RouterLink', rlComponent)
    return app
  }

  function replaceAnchors() {
    if (!container.value) {
      return
    }
    const anchors: HTMLCollectionOf<HTMLAnchorElement> = container.value.getElementsByTagName('a')
    Array.from(anchors).forEach((anchor: HTMLElement) => {
      // Attempt to create a NuxtLink from the anchor
      const nuxtLink = convertAnchor(anchor)
      if (nuxtLink) {
        // If successful replace the anchor with a span to act as the container for the component
        const parent = anchor.parentNode
        if (parent) {
          const linkContainer = document.createElement('span')
          parent.replaceChild(linkContainer, anchor)
          // mount the NuxtLink component in the span
          nuxtLink.mount(linkContainer)
        }
      }
    })
  }

  onMounted(() => {
    watchStopHandle = watch(container, replaceAnchors, {
      immediate: true,
    })
  })

  onBeforeUnmount(() => {
    watchStopHandle && watchStopHandle()
  })
}
